
import javax.swing.JTextField;

public class RIM_Frame extends javax.swing.JFrame {
   
   public static JTextField[][] matriz = new JTextField[7][7];
   public static JTextField[][] dominios = new JTextField[7][2];
   public static JTextField[][] ideales = new JTextField[7][2];
   public static JTextField[] pesos = new JTextField[7];

   public RIM_Frame(){
      
      initComponents();
      
      matriz[0][0] = A1_C1;matriz[0][1] = A1_C2;matriz[0][2] = A1_C3;matriz[0][3] = A1_C4;matriz[0][4] = A1_C5;matriz[0][5] = A1_C6;matriz[0][6] = A1_C7;
      matriz[1][0] = A2_C1;matriz[1][1] = A2_C2;matriz[1][2] = A2_C3;matriz[1][3] = A2_C4;matriz[1][4] = A2_C5;matriz[1][5] = A2_C6;matriz[1][6] = A2_C7;
      matriz[2][0] = A3_C1;matriz[2][1] = A3_C2;matriz[2][2] = A3_C3;matriz[2][3] = A3_C4;matriz[2][4] = A3_C5;matriz[2][5] = A3_C6;matriz[2][6] = A3_C7;
      matriz[3][0] = A4_C1;matriz[3][1] = A4_C2;matriz[3][2] = A4_C3;matriz[3][3] = A4_C4;matriz[3][4] = A4_C5;matriz[3][5] = A4_C6;matriz[3][6] = A4_C7;
      matriz[4][0] = A5_C1;matriz[4][1] = A5_C2;matriz[4][2] = A5_C3;matriz[4][3] = A5_C4;matriz[4][4] = A5_C5;matriz[4][5] = A5_C6;matriz[4][6] = A5_C7;
      matriz[5][0] = A6_C1;matriz[5][1] = A6_C2;matriz[5][2] = A6_C3;matriz[5][3] = A6_C4;matriz[5][4] = A6_C5;matriz[5][5] = A6_C6;matriz[5][6] = A6_C7;
      matriz[6][0] = A7_C1;matriz[6][1] = A7_C2;matriz[6][2] = A7_C3;matriz[6][3] = A7_C4;matriz[6][4] = A7_C5;matriz[6][5] = A7_C6;matriz[6][6] = A7_C7;
      
      dominios[0][0] = domI_1;dominios[0][1] = domF_1;
      dominios[1][0] = domI_2;dominios[1][1] = domF_2;
      dominios[2][0] = domI_3;dominios[2][1] = domF_3;
      dominios[3][0] = domI_4;dominios[3][1] = domF_4;
      dominios[4][0] = domI_5;dominios[4][1] = domF_5;
      dominios[5][0] = domI_6;dominios[5][1] = domF_6;
      dominios[6][0] = domI_7;dominios[6][1] = domF_7;
      
      ideales[0][0] = ideI_1;ideales[0][1] = ideF_1;
      ideales[1][0] = ideI_2;ideales[1][1] = ideF_2;
      ideales[2][0] = ideI_3;ideales[2][1] = ideF_3;
      ideales[3][0] = ideI_4;ideales[3][1] = ideF_4;
      ideales[4][0] = ideI_5;ideales[4][1] = ideF_5;
      ideales[5][0] = ideI_6;ideales[5][1] = ideF_6;
      ideales[6][0] = ideI_7;ideales[6][1] = ideF_7;
      
      pesos[0] = W1;
      pesos[1] = W2;
      pesos[2] = W3;
      pesos[3] = W4;
      pesos[4] = W5;
      pesos[5] = W6;
      pesos[6] = W7;
      
   }

   /**
    * This method is called from within the constructor to initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is always
    * regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jTextField106 = new javax.swing.JTextField();
      jTextField107 = new javax.swing.JTextField();
      jLabel16 = new javax.swing.JLabel();
      jPanel1 = new javax.swing.JPanel();
      A1_C1 = new javax.swing.JTextField();
      A1_C2 = new javax.swing.JTextField();
      A1_C3 = new javax.swing.JTextField();
      A1_C4 = new javax.swing.JTextField();
      A1_C5 = new javax.swing.JTextField();
      A1_C6 = new javax.swing.JTextField();
      A1_C7 = new javax.swing.JTextField();
      A2_C1 = new javax.swing.JTextField();
      A2_C2 = new javax.swing.JTextField();
      A3_C2 = new javax.swing.JTextField();
      A4_C1 = new javax.swing.JTextField();
      A4_C4 = new javax.swing.JTextField();
      A4_C3 = new javax.swing.JTextField();
      A2_C4 = new javax.swing.JTextField();
      A2_C3 = new javax.swing.JTextField();
      A3_C1 = new javax.swing.JTextField();
      A3_C4 = new javax.swing.JTextField();
      A3_C3 = new javax.swing.JTextField();
      A4_C2 = new javax.swing.JTextField();
      A5_C1 = new javax.swing.JTextField();
      A5_C2 = new javax.swing.JTextField();
      A5_C4 = new javax.swing.JTextField();
      A5_C3 = new javax.swing.JTextField();
      A6_C1 = new javax.swing.JTextField();
      A6_C2 = new javax.swing.JTextField();
      A6_C4 = new javax.swing.JTextField();
      A6_C3 = new javax.swing.JTextField();
      A7_C1 = new javax.swing.JTextField();
      A7_C2 = new javax.swing.JTextField();
      A7_C4 = new javax.swing.JTextField();
      A7_C3 = new javax.swing.JTextField();
      domF_1 = new javax.swing.JTextField();
      domI_2 = new javax.swing.JTextField();
      domI_3 = new javax.swing.JTextField();
      domI_4 = new javax.swing.JTextField();
      domI_5 = new javax.swing.JTextField();
      domI_6 = new javax.swing.JTextField();
      domI_7 = new javax.swing.JTextField();
      domI_1 = new javax.swing.JTextField();
      ideI_7 = new javax.swing.JTextField();
      ideF_2 = new javax.swing.JTextField();
      ideI_2 = new javax.swing.JTextField();
      ideI_4 = new javax.swing.JTextField();
      ideF_3 = new javax.swing.JTextField();
      ideI_3 = new javax.swing.JTextField();
      ideI_1 = new javax.swing.JTextField();
      ideF_1 = new javax.swing.JTextField();
      ideF_7 = new javax.swing.JTextField();
      ideF_6 = new javax.swing.JTextField();
      ideI_6 = new javax.swing.JTextField();
      ideF_4 = new javax.swing.JTextField();
      ideI_5 = new javax.swing.JTextField();
      ideF_5 = new javax.swing.JTextField();
      W5 = new javax.swing.JTextField();
      W6 = new javax.swing.JTextField();
      W7 = new javax.swing.JTextField();
      W3 = new javax.swing.JTextField();
      W1 = new javax.swing.JTextField();
      W4 = new javax.swing.JTextField();
      W2 = new javax.swing.JTextField();
      jLabel1 = new javax.swing.JLabel();
      jLabel2 = new javax.swing.JLabel();
      jLabel3 = new javax.swing.JLabel();
      jLabel4 = new javax.swing.JLabel();
      jLabel5 = new javax.swing.JLabel();
      jLabel6 = new javax.swing.JLabel();
      jLabel7 = new javax.swing.JLabel();
      jLabel8 = new javax.swing.JLabel();
      jLabel9 = new javax.swing.JLabel();
      jLabel10 = new javax.swing.JLabel();
      jLabel11 = new javax.swing.JLabel();
      jLabel12 = new javax.swing.JLabel();
      jLabel13 = new javax.swing.JLabel();
      jLabel14 = new javax.swing.JLabel();
      jLabel15 = new javax.swing.JLabel();
      jLabel17 = new javax.swing.JLabel();
      jLabel18 = new javax.swing.JLabel();
      jLabel19 = new javax.swing.JLabel();
      jLabel20 = new javax.swing.JLabel();
      jLabel21 = new javax.swing.JLabel();
      jLabel22 = new javax.swing.JLabel();
      jLabel23 = new javax.swing.JLabel();
      jLabel26 = new javax.swing.JLabel();
      A2_C5 = new javax.swing.JTextField();
      A3_C5 = new javax.swing.JTextField();
      A4_C5 = new javax.swing.JTextField();
      A5_C5 = new javax.swing.JTextField();
      A6_C5 = new javax.swing.JTextField();
      A7_C5 = new javax.swing.JTextField();
      A2_C6 = new javax.swing.JTextField();
      A3_C6 = new javax.swing.JTextField();
      A4_C6 = new javax.swing.JTextField();
      A5_C6 = new javax.swing.JTextField();
      A6_C6 = new javax.swing.JTextField();
      A7_C6 = new javax.swing.JTextField();
      A2_C7 = new javax.swing.JTextField();
      A3_C7 = new javax.swing.JTextField();
      A4_C7 = new javax.swing.JTextField();
      A5_C7 = new javax.swing.JTextField();
      A6_C7 = new javax.swing.JTextField();
      A7_C7 = new javax.swing.JTextField();
      domF_2 = new javax.swing.JTextField();
      domF_3 = new javax.swing.JTextField();
      domF_4 = new javax.swing.JTextField();
      domF_5 = new javax.swing.JTextField();
      domF_6 = new javax.swing.JTextField();
      domF_7 = new javax.swing.JTextField();
      jLabel24 = new javax.swing.JLabel();
      jLabel25 = new javax.swing.JLabel();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      alternativasBox = new javax.swing.JComboBox<>();
      criteriosBox = new javax.swing.JComboBox<>();

      jTextField106.setText("jTextField1");

      jTextField107.setText("jTextField1");

      jLabel16.setText("jLabel1");

      setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

      jLabel1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel1.setText("C 1");

      jLabel2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel2.setText("C 2");

      jLabel3.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel3.setText("C 3");

      jLabel4.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel4.setText("C 4");

      jLabel5.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel5.setText("C 5");

      jLabel6.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel6.setText("C 7");

      jLabel7.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel7.setText("C 6");

      jLabel8.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel8.setText("A 1");

      jLabel9.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel9.setText("A 2");

      jLabel10.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel10.setText("A 3");

      jLabel11.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel11.setText("A 4");

      jLabel12.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel12.setText("A 5");

      jLabel13.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel13.setText("A 6");

      jLabel14.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel14.setText("A 7");

      jLabel15.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel15.setText("Pesos");

      jLabel17.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel17.setText("W 3");

      jLabel18.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel18.setText("W 2");

      jLabel19.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel19.setText("W 1");

      jLabel20.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel20.setText("W 4");

      jLabel21.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel21.setText("W 5");

      jLabel22.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel22.setText("W 6");

      jLabel23.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel23.setText("W 7");

      jLabel26.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel26.setText("Metodo de RIM");

      jLabel24.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel24.setText("Dominio");

      jLabel25.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jLabel25.setText("Ideal de referencia");

      jButton1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jButton1.setText("Calcular");

      jButton2.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      jButton2.setText("Limpiar");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });

      alternativasBox.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      alternativasBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alternativas", "2", "3", "4", "5", "6", "7" }));
      alternativasBox.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            alternativasBoxActionPerformed(evt);
         }
      });

      criteriosBox.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
      criteriosBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Criterios", "2", "3", "4", "5", "6", "7" }));
      criteriosBox.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            criteriosBoxActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
      jPanel1.setLayout(jPanel1Layout);
      jPanel1Layout.setHorizontalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(57, 57, 57)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addComponent(jLabel8)
                     .addComponent(jLabel9)
                     .addComponent(jLabel10)
                     .addComponent(jLabel11)
                     .addComponent(jLabel12)
                     .addComponent(jLabel13)
                     .addComponent(jLabel14))
                  .addGap(18, 18, 18)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(A7_C1)
                        .addComponent(A6_C1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(A5_C1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(A4_C1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(A3_C1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(A2_C1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(A1_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(jLabel1))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel2)
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(A7_C2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A6_C2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A5_C2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A4_C2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A3_C2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A2_C2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A1_C2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel3)
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(A7_C3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A6_C3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A5_C3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A4_C3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A3_C3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A2_C3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A1_C3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(A1_C4)
                        .addComponent(A2_C4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(A3_C4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(A4_C4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A5_C4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A6_C4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(A7_C4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addComponent(jLabel4))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(A1_C5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A2_C5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A3_C5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A4_C5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A5_C5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A6_C5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A7_C5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel5))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(jLabel7)
                     .addComponent(A1_C6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A2_C6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A3_C6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A4_C6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A5_C6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A6_C6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A7_C6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addComponent(A2_C7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A3_C7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A5_C7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A6_C7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A7_C7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A4_C7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A1_C7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel6)))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addContainerGap()
                  .addComponent(jLabel15)
                  .addGap(18, 18, 18)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(W1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(W2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(W3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(W4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(jLabel21)
                           .addComponent(W5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(W6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(W7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(jLabel23)))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGap(30, 30, 30)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGap(50, 50, 50)
                  .addComponent(jLabel24)
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .addComponent(jLabel25)
                  .addGap(78, 78, 78))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(alternativasBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(criteriosBox, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(domI_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domI_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domI_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domI_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domI_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domI_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domI_7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addComponent(domF_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domF_7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domF_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domF_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domF_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domF_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domF_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                           .addGroup(jPanel1Layout.createSequentialGroup()
                              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                 .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ideI_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ideF_2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                 .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ideI_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ideF_1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                           .addGroup(jPanel1Layout.createSequentialGroup()
                              .addGap(32, 32, 32)
                              .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                 .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ideI_7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ideF_7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                 .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ideI_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ideF_6, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                 .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ideI_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ideF_5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                 .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ideI_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ideF_4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                 .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(ideI_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(ideF_3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                  .addGap(58, 58, 58))))
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
            .addGap(458, 458, 458)
            .addComponent(jLabel26)
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
      );
      jPanel1Layout.setVerticalGroup(
         jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(28, 28, 28)
            .addComponent(jLabel26)
            .addGap(31, 31, 31)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jLabel1)
                  .addComponent(jLabel2)
                  .addComponent(jLabel4)
                  .addComponent(jLabel3))
               .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel7)
                  .addComponent(jLabel5)
                  .addComponent(jLabel6)
                  .addComponent(jLabel24)
                  .addComponent(jLabel25)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(A1_C5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(A1_C6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(A1_C7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(domI_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(A1_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel8)
                     .addComponent(A1_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(A2_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel9)
                     .addComponent(A2_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(A3_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel10)
                     .addComponent(A3_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(A4_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel11)
                     .addComponent(A4_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(A5_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel12)
                     .addComponent(A5_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(A6_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel13)
                     .addComponent(A6_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(A7_C1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(jLabel14)
                     .addComponent(A7_C2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A7_C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A7_C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A7_C5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A7_C6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(A7_C7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(domI_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(domF_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
               .addComponent(domF_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addGroup(jPanel1Layout.createSequentialGroup()
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                     .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(A1_C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A1_C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(A2_C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A2_C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A2_C5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A2_C6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A2_C7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domI_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domF_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(ideI_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(ideF_2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(A3_C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A3_C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A3_C5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A3_C6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A3_C7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domI_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domF_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(ideI_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(ideF_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(A4_C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A4_C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A4_C5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A4_C6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A4_C7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domI_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domF_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(ideI_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(ideF_4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(A5_C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A5_C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A5_C5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A5_C6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A5_C7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domI_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domF_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(ideI_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(ideF_5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                           .addComponent(A6_C3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A6_C4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A6_C5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A6_C6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(A6_C7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domI_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(domF_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(ideI_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                           .addComponent(ideF_6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                     .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ideI_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ideF_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                  .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                  .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                     .addComponent(ideI_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                     .addComponent(ideF_7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(W1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(W2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(W3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(W4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(W5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(W6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(W7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(jLabel15)
               .addComponent(alternativasBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
               .addComponent(criteriosBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                  .addComponent(jLabel17)
                  .addComponent(jLabel20)
                  .addComponent(jLabel21)
                  .addComponent(jLabel22)
                  .addComponent(jLabel23))
               .addComponent(jLabel19)
               .addComponent(jLabel18))
            .addGap(32, 32, 32)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
               .addComponent(jButton1)
               .addComponent(jButton2))
            .addContainerGap(36, Short.MAX_VALUE))
      );

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

   private void alternativasBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alternativasBoxActionPerformed
      
      String alternativasStr = alternativasBox.getSelectedItem().toString();
      String criteriosStr = criteriosBox.getSelectedItem().toString();
      
      int a = 0;
      int c = 0;
      
      if(alternativasStr.compareTo("Alternativas") != 0){
         a = Integer.parseInt(alternativasStr);
         c = criteriosStr.compareTo("Criterios") != 0 ? Integer.parseInt(criteriosStr) : 7;
         cambioMatriz(a, c);
         cambioDominios(a);
         cambioIdeales(a);
      }
      
   }//GEN-LAST:event_alternativasBoxActionPerformed

   private void criteriosBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criteriosBoxActionPerformed
      
      String alternativasStr = alternativasBox.getSelectedItem().toString();
      String criteriosStr = criteriosBox.getSelectedItem().toString();
      
      int a = 0;
      int c = 0;
      
      if(criteriosStr.compareTo("Criterios") != 0){
         c = Integer.parseInt(criteriosStr);
         a = alternativasStr.compareTo("Alternativas") != 0 ? Integer.parseInt(alternativasStr) : 7;
         cambioMatriz(a, c);
         cambioPesos(c);
      }
      
   }//GEN-LAST:event_criteriosBoxActionPerformed

   private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      
      for (int i = 0; i < 7; i++) {
         for (int j = 0; j < 7; j++) {
            matriz[i][j].setText("");
            
         }
         for (int j = 0; j < 2; j++) {
            dominios[i][j].setText("");
            ideales[i][j].setText("");
         }
         pesos[i].setText("");
      }
      
   }//GEN-LAST:event_jButton2ActionPerformed

   /**
    * @param args the command line arguments
    */
   public static void main(String args[]) {
      /* Set the Nimbus look and feel */
      //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
      /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
       */
      try {
         for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
               javax.swing.UIManager.setLookAndFeel(info.getClassName());
               break;
            }
         }
      } catch (ClassNotFoundException ex) {
         java.util.logging.Logger.getLogger(RIM_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (InstantiationException ex) {
         java.util.logging.Logger.getLogger(RIM_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (IllegalAccessException ex) {
         java.util.logging.Logger.getLogger(RIM_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      } catch (javax.swing.UnsupportedLookAndFeelException ex) {
         java.util.logging.Logger.getLogger(RIM_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
      }
      //</editor-fold>

      /* Create and display the form */
      java.awt.EventQueue.invokeLater(new Runnable() {
         public void run() {
            new RIM_Frame().setVisible(true);
         }
      });
   }
   
   public static void cambioMatriz(int a, int c){
      for(int i = a; i < 7; i++){
         for (int j = 0; j < 7; j++) {
            matriz[i][j].setText("");
            matriz[i][j].setEnabled(false);
         }
      }
      for(int i = 0; i < 7; i++){
         for (int j = c; j < 7; j++) {
            matriz[i][j].setText("");
            matriz[i][j].setEnabled(false);
         }
      }
      for(int i = 0; i < a; i++){
         for (int j = 0; j < c; j++){
            matriz[i][j].setEnabled(true);
         }
      }
   }
   
   public static void cambioDominios(int a){
      for(int i = a; i < 7; i++){
         for(int j = 0; j < 2; j++){
            dominios[i][j].setText("");
            dominios[i][j].setEnabled(false);
         }
      }
      for(int i = 0; i < a; i++){
         for(int j = 0; j < 2; j++){
            dominios[i][j].setEnabled(true);
         }
      }
   }
   
   public static void cambioIdeales(int a){
      for(int i = a; i < 7; i++){
         for(int j = 0; j < 2; j++){
            ideales[i][j].setText("");
            ideales[i][j].setEnabled(false);
         }
      }
      for(int i = 0; i < a; i++){
         for(int j = 0; j < 2; j++){
            ideales[i][j].setEnabled(true);
         }
      }
   }
   
   public static void cambioPesos(int c){
      for(int i = c; i < 7; i++) {
         pesos[i].setText("");
         pesos[i].setEnabled(false);
      }
      for(int i = 0; i < c; i++) {
         pesos[i].setEnabled(true);
      }
   }

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JTextField A1_C1;
   private javax.swing.JTextField A1_C2;
   private javax.swing.JTextField A1_C3;
   private javax.swing.JTextField A1_C4;
   private javax.swing.JTextField A1_C5;
   private javax.swing.JTextField A1_C6;
   private javax.swing.JTextField A1_C7;
   private javax.swing.JTextField A2_C1;
   private javax.swing.JTextField A2_C2;
   private javax.swing.JTextField A2_C3;
   private javax.swing.JTextField A2_C4;
   private javax.swing.JTextField A2_C5;
   private javax.swing.JTextField A2_C6;
   private javax.swing.JTextField A2_C7;
   private javax.swing.JTextField A3_C1;
   private javax.swing.JTextField A3_C2;
   private javax.swing.JTextField A3_C3;
   private javax.swing.JTextField A3_C4;
   private javax.swing.JTextField A3_C5;
   private javax.swing.JTextField A3_C6;
   private javax.swing.JTextField A3_C7;
   private javax.swing.JTextField A4_C1;
   private javax.swing.JTextField A4_C2;
   private javax.swing.JTextField A4_C3;
   private javax.swing.JTextField A4_C4;
   private javax.swing.JTextField A4_C5;
   private javax.swing.JTextField A4_C6;
   private javax.swing.JTextField A4_C7;
   private javax.swing.JTextField A5_C1;
   private javax.swing.JTextField A5_C2;
   private javax.swing.JTextField A5_C3;
   private javax.swing.JTextField A5_C4;
   private javax.swing.JTextField A5_C5;
   private javax.swing.JTextField A5_C6;
   private javax.swing.JTextField A5_C7;
   private javax.swing.JTextField A6_C1;
   private javax.swing.JTextField A6_C2;
   private javax.swing.JTextField A6_C3;
   private javax.swing.JTextField A6_C4;
   private javax.swing.JTextField A6_C5;
   private javax.swing.JTextField A6_C6;
   private javax.swing.JTextField A6_C7;
   private javax.swing.JTextField A7_C1;
   private javax.swing.JTextField A7_C2;
   private javax.swing.JTextField A7_C3;
   private javax.swing.JTextField A7_C4;
   private javax.swing.JTextField A7_C5;
   private javax.swing.JTextField A7_C6;
   private javax.swing.JTextField A7_C7;
   private javax.swing.JTextField W1;
   private javax.swing.JTextField W2;
   private javax.swing.JTextField W3;
   private javax.swing.JTextField W4;
   private javax.swing.JTextField W5;
   private javax.swing.JTextField W6;
   private javax.swing.JTextField W7;
   private javax.swing.JComboBox<String> alternativasBox;
   private javax.swing.JComboBox<String> criteriosBox;
   private javax.swing.JTextField domF_1;
   private javax.swing.JTextField domF_2;
   private javax.swing.JTextField domF_3;
   private javax.swing.JTextField domF_4;
   private javax.swing.JTextField domF_5;
   private javax.swing.JTextField domF_6;
   private javax.swing.JTextField domF_7;
   private javax.swing.JTextField domI_1;
   private javax.swing.JTextField domI_2;
   private javax.swing.JTextField domI_3;
   private javax.swing.JTextField domI_4;
   private javax.swing.JTextField domI_5;
   private javax.swing.JTextField domI_6;
   private javax.swing.JTextField domI_7;
   private javax.swing.JTextField ideF_1;
   private javax.swing.JTextField ideF_2;
   private javax.swing.JTextField ideF_3;
   private javax.swing.JTextField ideF_4;
   private javax.swing.JTextField ideF_5;
   private javax.swing.JTextField ideF_6;
   private javax.swing.JTextField ideF_7;
   private javax.swing.JTextField ideI_1;
   private javax.swing.JTextField ideI_2;
   private javax.swing.JTextField ideI_3;
   private javax.swing.JTextField ideI_4;
   private javax.swing.JTextField ideI_5;
   private javax.swing.JTextField ideI_6;
   private javax.swing.JTextField ideI_7;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel10;
   private javax.swing.JLabel jLabel11;
   private javax.swing.JLabel jLabel12;
   private javax.swing.JLabel jLabel13;
   private javax.swing.JLabel jLabel14;
   private javax.swing.JLabel jLabel15;
   private javax.swing.JLabel jLabel16;
   private javax.swing.JLabel jLabel17;
   private javax.swing.JLabel jLabel18;
   private javax.swing.JLabel jLabel19;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JLabel jLabel20;
   private javax.swing.JLabel jLabel21;
   private javax.swing.JLabel jLabel22;
   private javax.swing.JLabel jLabel23;
   private javax.swing.JLabel jLabel24;
   private javax.swing.JLabel jLabel25;
   private javax.swing.JLabel jLabel26;
   private javax.swing.JLabel jLabel3;
   private javax.swing.JLabel jLabel4;
   private javax.swing.JLabel jLabel5;
   private javax.swing.JLabel jLabel6;
   private javax.swing.JLabel jLabel7;
   private javax.swing.JLabel jLabel8;
   private javax.swing.JLabel jLabel9;
   private javax.swing.JPanel jPanel1;
   private javax.swing.JTextField jTextField106;
   private javax.swing.JTextField jTextField107;
   // End of variables declaration//GEN-END:variables
}
